name: Build & Deploy RoRo Frontend

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - "wp-content/plugins/roro-core/src/**"
      - ".github/workflows/build.yml"
  workflow_dispatch:

env:
  NODE_VERSION: "18.x"
  PNPM_VERSION: "9"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - uses: actions/checkout@v4

      # set up Node / pnpm
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: "Install pnpm"
        run: npm install -g pnpm@${{ env.PNPM_VERSION }}

      # install deps
      - name: "Install dependencies"
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      # lint & test
      - name: "Lint"
        working-directory: frontend
        run: pnpm run lint

      - name: "Unit tests"
        working-directory: frontend
        run: pnpm run test:unit -- --run

      - name: "E2E tests (Playwright)"
        working-directory: frontend
        run: pnpm run test:e2e -- --reporter=line

      # build production assets
      - name: "Build frontend"
        working-directory: frontend
        run: pnpm run build

      # copy assets into plugin folder
      - name: "Sync built assets to plugin"
        run: |
          mkdir -p wp-content/plugins/roro-core/assets/build
          rsync -av --delete \
              frontend/dist/ \
              wp-content/plugins/roro-core/assets/build/

      # archive artefact
      - name: "Upload artefact"
        uses: actions/upload-artifact@v4
        with:
          name: roro-plugin-build
          path: |
            wp-content/plugins/roro-core/assets/build
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: "Download artefact"
        uses: actions/download-artifact@v4
        with:
          name: roro-plugin-build
          path: wp-content/plugins/roro-core/assets/build

      # deploy via SFTP to Xserver (secrets must be set in repo)
      - name: "Deploy to Xserver"
        uses: presslabs/ftp-deploy@v1
        with:
          host: ${{ secrets.XS_HOST }}
          user: ${{ secrets.XS_USER }}
          password: ${{ secrets.XS_PASS }}
          local-dir: wp-content/plugins/roro-core/assets/build
          server-dir: /public_html/wp-content/plugins/roro-core/assets/build
          protocol: sftp
