/* eslint-disable no-undef */
/* ****************************************************
 * service-worker.js – generated by Workbox v7 + FCM
 * ***************************************************/

/* --- Workbox precache manifest（自動挿入領域）--- */
self.__WB_DISABLE_DEV_LOGS = true;
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');
workbox.setConfig({ debug: false });

workbox.precaching.precacheAndRoute(self.__WB_MANIFEST || []);

/* --- Runtime caching  --------------------------------------- */
workbox.routing.registerRoute(
  ({ url }) => url.pathname.startsWith('/wp-json/roro/'),
  new workbox.strategies.NetworkFirst({
    cacheName: 'roro-api',
    networkTimeoutSeconds: 3,
  }),
);

/* --- Firebase Cloud Messaging (Push) ------------------------- */
importScripts('https://www.gstatic.com/firebasejs/10.5.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.5.0/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: '%%FIREBASE_API_KEY%%',
  projectId: '%%FIREBASE_PROJECT_ID%%',
  messagingSenderId: '%%FIREBASE_SENDER_ID%%',
  appId: '%%FIREBASE_APP_ID%%',
});
const messaging = firebase.messaging();

/* 受信した push 通知を表示 */
messaging.onBackgroundMessage(({ notification }) => {
  self.registration.showNotification(notification.title, notification);
});

/* 通知クリック時に URL を開く */
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = event.notification.data?.url || '/';
  event.waitUntil(clients.openWindow(url));
});
