-- RORO 初期テーブル作成（必要十分の最小構成）
-- エンジン/文字コードは環境に合わせて調整
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_CUSTOMER (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  wp_user_id BIGINT UNSIGNED NULL,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  phone VARCHAR(64) NULL,
  country VARCHAR(64) NULL,
  prefecture VARCHAR(64) NULL,
  address1 VARCHAR(191) NULL,
  address2 VARCHAR(191) NULL,
  language_code VARCHAR(8) DEFAULT 'ja',
  default_pet_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_customer_email (email),
  KEY idx_wp_user (wp_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_PET (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(191) NOT NULL,
  kind VARCHAR(64) NOT NULL DEFAULT 'dog',
  breed VARCHAR(191) NULL,
  birthdate DATE NULL,
  weight DECIMAL(6,2) NULL,
  image_url VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_customer (customer_id),
  CONSTRAINT fk_pet_customer FOREIGN KEY (customer_id) REFERENCES RORO_CUSTOMER(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_BREED_MASTER (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  kind VARCHAR(64) NOT NULL DEFAULT 'dog',
  breed_name VARCHAR(191) NOT NULL,
  lang VARCHAR(8) NOT NULL DEFAULT 'ja',
  UNIQUE KEY uq_breed (kind, breed_name, lang)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_EVENTS_MASTER (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(191) NOT NULL,
  description TEXT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  address VARCHAR(255) NULL,
  city VARCHAR(128) NULL,
  prefecture VARCHAR(64) NULL,
  category VARCHAR(64) NULL,
  url VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_time (start_time),
  KEY idx_geo (latitude, longitude)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_MAP_FAVORITE (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NOT NULL,
  event_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_fav (customer_id, event_id),
  KEY idx_customer (customer_id),
  KEY idx_event (event_id),
  CONSTRAINT fk_fav_customer FOREIGN KEY (customer_id) REFERENCES RORO_CUSTOMER(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_ONE_POINT_ADVICE_MASTER (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(64) NOT NULL DEFAULT 'general',
  advice_text TEXT NOT NULL,
  lang VARCHAR(8) NOT NULL DEFAULT 'ja',
  weight INT NOT NULL DEFAULT 100,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_active (active),
  KEY idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_AI_CONVERSATION (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_interaction_at DATETIME NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  metadata JSON NULL,
  KEY idx_cus (customer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_AI_MESSAGE (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  conversation_id BIGINT UNSIGNED NOT NULL,
  role ENUM('user','assistant','system') NOT NULL DEFAULT 'user',
  content LONGTEXT NOT NULL,
  token_count INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_conv (conversation_id),
  CONSTRAINT fk_msg_conv FOREIGN KEY (conversation_id) REFERENCES RORO_AI_CONVERSATION(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_USER_LINK_WP (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  wp_user_id BIGINT UNSIGNED NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  provider VARCHAR(32) NULL,
  provider_user_id VARCHAR(191) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_wpuser (wp_user_id),
  UNIQUE KEY uq_provider (provider, provider_user_id),
  KEY idx_customer (customer_id),
  CONSTRAINT fk_link_customer FOREIGN KEY (customer_id) REFERENCES RORO_CUSTOMER(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RORO_AUTH_ACCOUNT (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  provider VARCHAR(32) NOT NULL,
  provider_user_id VARCHAR(191) NOT NULL,
  email VARCHAR(191) NULL,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at DATETIME NULL,
  UNIQUE KEY uq_auth (provider, provider_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
