# docker/docker-compose.yml
version: "3.9"

services:
  db:
    image: mysql:8.3
    container_name: roro_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wpuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wppass}
    volumes:
      - db_data:/var/lib/mysql
    networks: [wpnet]

  wordpress:
    build: ./php
    container_name: roro_wp
    depends_on: [db]
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - ../:/var/www/html/wp-content/plugins/roro-core
      - wp_data:/var/www/html
    networks: [wpnet]

  nginx:
    build: ./nginx
    container_name: roro_nginx
    depends_on: [wordpress]
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html:ro
    networks: [wpnet]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: unless-stopped
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
    networks: [wpnet]

  mailhog:
    image: mailhog/mailhog:v1.0
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks: [wpnet]

volumes:
  db_data:
  wp_data:

networks:
  wpnet:
