# プルリクエストごとに Lint + Unit Test を実行
name: CI – Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 8 }
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test:unit -- --runInBand
