# PHP_CodeSniffer + ESLint を定期実行
name: CI – Lint

on:
  schedule:
    - cron: '0 3 * * 1'   # 毎週月曜 12:00 JST
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - run: composer install --no-dev
      - run: vendor/bin/phpcs --standard=WordPress ./wp-content/plugins/roro-core
      - uses: pnpm/action-setup@v3
        with: { version: 8 }
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint:js
